# Generated by Django 5.0.3 on 2024-04-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="rol",
            field=models.CharField(
                choices=[
                    ("estudiante", "Estudiante"),
                    ("instructor", "Instructor"),
                    ("admin", "Administrador"),
                ],
                default="estudiante",
                max_length=20,
            ),
        ),
    ]
