# Generated by Django 5.0.3 on 2024-03-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0003_curso_destacado_curso_requisitos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("bio", models.TextField()),
            ],
        ),
    ]
