# Generated by Django 5.0.3 on 2024-03-26 21:50

import cursos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0004_instructor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="curso",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cursos.instructor",
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="estado",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("publicado", "Publicado"),
                    ("archivado", "Archivado"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="precio",
            field=models.IntegerField(validators=[cursos.models.precio_positivo]),
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inscripcion", models.DateField(auto_now_add=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cursos.curso"
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cursos.estudiante",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="curso",
            name="estudiantes",
            field=models.ManyToManyField(
                through="cursos.Inscripcion", to="cursos.estudiante"
            ),
        ),
    ]
