# Generated by Django 5.0.3 on 2024-03-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0005_estudiante_curso_instructor_alter_curso_estado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscripcion",
            name="fecha_inscripcion",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name="inscripcion",
            unique_together={("estudiante", "curso")},
        ),
    ]
